### ISSUE TITLE
Orders table

### ISSUE THREAD

**Issue by carminio** [atls/iheal#14]
### Задача
Сделать фрагмент [orders table](https://www.figma.com/file/DVbIP4cBkLufAPajn41ylk/Design?node-id=317%3A67604&t=iqmcG8fAciJnfzdz-4)

**Comment by carminio** [comment]
## Не обновляется стейт в реактивной переменной

@TFK70 

### Описание
Есть [фильтры](https://github.com/atls/iheal/blob/feat/init-front/app/fragments/controls/src/filters/filters.component.tsx) которые влияют на айтемы в таблице, всё по классике
Есть [хук](https://github.com/atls/iheal/blob/feat/init-front/app/fragments/orders-table/src/hooks/use-filtered-orders.hook.ts) в котором реализовываю логику фильтрации, в этом файле есть [console.log](https://github.com/atls/iheal/blob/feat/init-front/app/fragments/orders-table/src/hooks/use-filtered-orders.hook.ts#L29) в котором находится переменная status и когда добавляешь айтемы в эту переменную, то они в ней не отображаются, но вот интересный момент, в компоненте [Filters](https://github.com/atls/iheal/blob/feat/init-front/app/fragments/controls/src/filters/filters.component.tsx#L43) если залогать ту же переменную, можно увидеть что она обновляется и айтемы туда добавляются

### Шаги воспроизведения
1. поднять сайт
2. нажать на кнопку фильтры
3. в селекте Статус выбрать какой нибудь статус и смотреть в логи

### Ожидаемое поведение
Состояние в переменной обновляется

### Вопрос
Из-за чего не обновляется стейт? Я может чего-то в упор не вижу, либо здесь что-то посерьезнее

**Comment by carminio** [comment]
## Проблема со слоями 

@TFK70 

### Описание
Есть drawer в котором можно сделать новый заказ, в этом drawere есть селекты, при нажатии на селект должен появляться dropdown с айтемами, но он не отображается, в плане он есть, но слоем ниже drawer'a, понять это можно след. образом - уменьшить opacity у бекграунда drawer'a и тогда будет видно что dropdown у селекта находится ниже по Z индексу, казалось бы проблема смешная, но куда я только этот zIndex не вставлял для дропдауна чтобы он перекрыл zIndex drawer'a 

### Шаги воспроизведения
1. поднять сайт
2. нажать на кнопку + Новый заказ, которая находится возле поиска слева
3. Нажать на любой селект в drawer'e

### Ожидаемое поведение
Dropdown селекта появляется поверх drawer'a

### Вопрос
Как пофиксить)

**Comment by LIMPIX31** [comment]
> ## Проблема со слоями
> 
> @TFK70
> ### Описание
> 
> Есть drawer в котором можно сделать новый заказ, в этом drawere есть селекты, при нажатии на селект должен появляться dropdown с айтемами, но он не отображается, в плане он есть, но слоем ниже drawer'a, понять это можно след. образом - уменьшить opacity у бекграунда drawer'a и тогда будет видно что dropdown у селекта находится ниже по Z индексу, казалось бы проблема смешная, но куда я только этот zIndex не вставлял для дропдауна чтобы он перекрыл zIndex drawer'a
> ### Шаги воспроизведения
> 
>     1. поднять сайт
> 
>     2. нажать на кнопку + Новый заказ, которая находится возле поиска слева
> 
>     3. Нажать на любой селект в drawer'e
> 
> 
> ### Ожидаемое поведение
> 
> Dropdown селекта появляется поверх drawer'a
> ### Материалы
> 
> Код из New Order - [link](https://github.com/atls/iheal/blob/feat/init-front/app/fragments/new-order/src/customer-contact-information/customer-contact-information.component.tsx). Но думаю он особо то и не нужен, тк дело в компоненте самого селекта `@ui/select`, а именно [menu](https://github.com/atls/iheal/blob/feat/init-front/ui/select/src/menu/menu.styles.ts) и [menu-multiselect](https://github.com/atls/iheal/blob/feat/init-front/ui/select/src/menu-multiselect/menu-multiselect.styles.ts)
> ### Вопрос
> 
> Как пофиксить)

Выпадающий список селекта отображается в [портале](https://reactjs.org/docs/portals.html), а значит не является дочерним элементом drawer'а. 
```html
<div id="layers" style="position: absolute; top: 0px; left: 0px; right: 0px;"/>
```
Его `z-index` наследуется от `body`, поскольку он не установлен в `body`, то `z-index` элемента в портале равен нулю. А вот `z-index` drawer'а - 900. Соответственно нужно изменить `z-index` элемента в портале.

Layer для меню создаётся при помощи `react-laag` и используется внутри [@atls-ui-parts/select](https://github.com/atls/uikit/blob/master/ui-parts/select/src/use-select.hook.tsx#L36). Не то что бы я нашёл где изменить стили, но нужно думать в этом направлении. Я изменил `z-index` через devtools и это сработало.
